import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/style.css";
import { NavigationMenuDemo } from "./layouts/navbar";
import { TypographyH4 } from "@/components/ui/typhography";
import { ButtonDefault } from "@/components/ui/default-button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Menu } from "lucide-react";
import { Footer2 } from "@/components/ui/footer";
import "./footerStyle/style.css";
import { Footer3 } from "@/components/ui/footer3";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full py-4 sticky top-0 bg-[hsl(var(--background)/0.8)] backdrop-blur-[12px] z-50 transition-all">
          <div className="container mx-auto flex items-center justify-between px-4">
           
            <div className="flex items-center gap-3 md:flex-1">
              <Avatar>
                <AvatarImage src="https://avatars.githubusercontent.com/u/6880091?v=4" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <TypographyH4 />
            </div>

            <div className="hidden md:flex md:flex-1 justify-center">
              <NavigationMenuDemo />
            </div>

            <div className="flex items-center gap-2 md:flex-1 md:justify-end">
              <button className="p-2 md:hidden flex items-center gap-3 md:flex-1">
                <span className="  text-lg leading-none font-medium">Menu</span>
                <Menu className="w-6 h-6" 
                />
                
              </button>

              <div className="hidden md:block">
                <ButtonDefault />
              </div>
            </div>
          </div>
        </div>

        {children}
    
        <footer>
        <Footer3/>
      </footer>
      
      </body>
      
    </html>
  );
}
